---
- hosts: localhost
  user: ansible
  become: yes
  connection: ssh

  tasks:
    - name: getting link from jenkins.io
      get_url:
        url:  https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo 

    - name: getting keys from jenkins
      ansible.builtin.rpm_key :
        state: present
        key:  https://pkg.jenkins.io/redhat-stable/jenkins.io.key

    - name: update these two links
      action: yum name="*" state=latest

    - name: install java
      command: amazon-linux-extras install java-openjdk11 -y

    - name: install jenkins
      command: yum install jenkins -y

    - name: reload daemon
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: restart jenkins
      ansible.builtin.systemd:
        name: jenkins
        state: restarted


